# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_warrior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='habitat',
            field=models.CharField(default='forest', max_length=20),
        ),
    ]
