# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_warrior', '0003_cat_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='habitat',
            field=models.CharField(choices=[('H', 'Hills'), ('P', 'Pines'), ('G', 'Gorge'), ('M', 'Moor'), ('R', 'River'), ('L', 'Lake'), ('F', 'Forest')], default='F', max_length=1),
        ),
    ]
