# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_warrior', '0004_auto_20160430_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='position',
            field=models.CharField(choices=[('LD', 'Leader'), ('DY', 'Deputy'), ('WR', 'Warrior'), ('AP', 'Apprentice'), ('MC', 'Medicine Cat'), ('MCA', 'Medicine Cat Apprentice'), ('ED', 'Elder'), ('QU', 'Queen'), ('KT', 'Kit')], default='WR', max_length=3),
        ),
    ]
