# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_warrior', '0006_cat_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='intelligence',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='cat',
            name='strength',
            field=models.IntegerField(default=35),
        ),
    ]
