# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_warrior', '0007_auto_20160710_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='agility',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='attentiveness',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='cleverness',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='climbing',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='fighting',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='health',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='hunting',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='jumping',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='leadership',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='cat',
            name='obedience',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='peception',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='running',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='sensitivity',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='speed',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='cat',
            name='stealth',
            field=models.IntegerField(default=35),
        ),
    ]
