# Generated by Django 2.0.2 on 2018-02-26 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_warrior', '0010_cat_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='photo',
        ),
    ]
