# Generated by Django 2.0.2 on 2018-02-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_warrior', '0011_remove_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(default=1234, upload_to='cats'),
            preserve_default=False,
        ),
    ]
